# Generated by Django 3.2.20 on 2023-12-06 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0085_alter_resourcebase_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteGeoNodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=1024)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Remote GeoNode Instance',
            },
        ),
        migrations.CreateModel(
            name='RemotePushSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('force', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ABORTING', 'aborting'), ('ABORTED', 'aborted'), ('PARTIAL_FAILURE', 'partial failure')], default='PENDING', max_length=50)),
                ('total_resources_to_process', models.IntegerField(default=0, help_text='Number of resources being processed in this session')),
                ('resources_done', models.IntegerField(default=0, help_text='Number of resources that have already been processed')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.remotegeonodeinstance')),
            ],
            options={
                'verbose_name': 'Remote Push Session',
            },
        ),
        migrations.CreateModel(
            name='RemotePushJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ABORTING', 'aborting'), ('ABORTED', 'aborted')], default='PENDING', max_length=50)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resourcebase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.remotepushsession')),
            ],
            options={
                'verbose_name': 'Remote Push Job',
            },
        ),
    ]
