# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_auto_20190516_0909'),
        ('layers', '0027_auto_20170801_1228_squashed_0033_auto_20180606_1543'),
        ('documents', '0029_auto_20190429_0831'),
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas',
            name='resources',
        ),
        migrations.AddField(
            model_name='atlas',
            name='documents',
            field=models.ManyToManyField(related_name='document_collections', to='documents.Document'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='jumbotronBackgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m', verbose_name='Atlas Jumbotron background'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='layers',
            field=models.ManyToManyField(related_name='layer_collections', to='layers.Layer'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='maps',
            field=models.ManyToManyField(related_name='map_collections', to='maps.Map'),
        ),
        migrations.AddField(
            model_name='atlas',
            name='primer',
            field=models.TextField(default='primer'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='content',
            field=models.TextField(default='content'),
        ),
    ]
