# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_auto_20191101_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='jumbotronBackgroundMovie',
            field=models.FileField(blank=True, null=True, upload_to='atlas/mov/%Y/%m', verbose_name='Atlas Jumbotron background movie'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='jumbotronBackgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='atlas/img/%Y/%m', verbose_name='Atlas Jumbotron background image'),
        ),
    ]
