# Generated by Django 2.2.10 on 2020-02-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_auto_20191104_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_collections', to='groups.GroupProfile'),
        ),
    ]
