# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_auto_20200210_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_collections', to='groups.GroupProfile'),
        ),
    ]
