# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0006_auto_20200214_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='customApps',
            field=models.ManyToManyField(blank=True, null=True, related_name='customApp_collections', to='atlas.CustomApplication'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, related_name='document_collections', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='layers',
            field=models.ManyToManyField(blank=True, null=True, related_name='layer_collections', to='layers.Layer'),
        ),
        migrations.AlterField(
            model_name='atlas',
            name='maps',
            field=models.ManyToManyField(blank=True, null=True, related_name='map_collections', to='maps.Map'),
        ),
    ]
