# Generated by Django 2.2.20 on 2021-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
        ('atlas', '0007_auto_20200214_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas',
            name='group',
        ),
        migrations.AddField(
            model_name='atlas',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_collections', to='groups.GroupProfile'),
        ),
    ]
