# Generated by Django 2.2.20 on 2021-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapps', '0001_initial'),
        ('atlas', '0008_auto_20210618_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='geoApps',
            field=models.ManyToManyField(blank=True, null=True, related_name='geoapp_collections', to='geoapps.GeoApp'),
        ),
    ]
