# Generated by Django 2.2.24 on 2021-12-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0009_atlas_geoapps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasCustomAppListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='atlas',
            name='customApps',
        ),
        migrations.AddField(
            model_name='atlas',
            name='customApps',
            field=models.ManyToManyField(blank=True, null=True, related_name='customApp_collections', through='atlas.AtlasCustomAppListing', to='atlas.CustomApplication'),
        ),
        migrations.AddField(
            model_name='atlascustomapplisting',
            name='atlas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.Atlas'),
        ),
        migrations.AddField(
            model_name='atlascustomapplisting',
            name='customApp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas.CustomApplication'),
        ),
    ]
