version: '3.4'

services:
  django:
    restart: "no"
    env_file: ./.devcontainer/.env.local
    volumes:
      - ./.devcontainer/_gitignore:/usr/src/geonode/.gitignore
      - ./.devcontainer/_vscode:/usr/src/geonode/.vscode
    ports:
      - "8001:8001"
    command: sleep infinity

  celery:
    restart: "no"
    depends_on:
      - django
    # volumes:
    #   - './src:/usr/src/geonode'

  geoserver:
    build:
      context: ./.devcontainer/docker/geoserver
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_BASE_IMAGE_VERSION}
    env_file: ./.devcontainer/.env.local
    ports:
      - "8080:8080"

  db:
    build:
      context: ./.devcontainer/docker/postgresql
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
