version: '3.4'
services:
  django:
    restart: "no"

    healthcheck:
      test: "echo \"I'm alive.\""

    env_file:
      - .devcontainer/.env

    # volumes:
    #   # Update this to wherever you want VS Code to mount the folder of your project
    #   - './src:/usr/src/thuenen_atlas'
    #   - '../geonode:/usr/src/geonode'
    #   - '../geonode-mapstore-client:/usr/src/geonode-mapstore-client'
    #   - '../geonode-importer:/usr/src/geonode-importer'
    #   # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
    #   # - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    ports:
      - "8000:8000"
      - "8001:8001"
    command: sleep infinity

  celery:
    restart: "no"
    env_file:
      - .devcontainer/.env
    # volumes:
    #   - './src:/usr/src/geonode'

  geonode:
    env_file:
      - .devcontainer/.env

  geoserver:
    env_file:
      - .devcontainer/.env

    ports:
      - "8080:8080"

  db:
    env_file:
      - .devcontainer/.env

    ports:
     - "5432:5432"

  rabbitmq:
    env_file:
      - .devcontainer/.env
